//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _800Best.ExcelHelpModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class cost
    {
        public string 运单编号 { get; set; }
        public string 结算类型 { get; set; }
        public System.DateTime 结算_上传日期 { get; set; }
        public double 结算流水号 { get; set; }
        public double 金额 { get; set; }
        public string 入账余额 { get; set; }
        public string 备注 { get; set; }
    }
}
