//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _800Best.ExcelHelpModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public System.DateTime 入网日期 { get; set; }
        public string 运单号 { get; set; }
        public string 电子面单打印 { get; set; }
        public string 电商下单 { get; set; }
        public string 签收目的地 { get; set; }
        public Nullable<double> 重量 { get; set; }
        public string 归属站点 { get; set; }
        public Nullable<double> 分拨中心称重 { get; set; }
        public Nullable<double> 集散仓称重 { get; set; }
        public Nullable<double> 一级站点称重 { get; set; }
        public Nullable<double> 二级站点称重 { get; set; }
        public Nullable<double> 计泡重量 { get; set; }
    }
}
