//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _800Best.ExcelHelpEFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Cost = new HashSet<Cost>();
            this.Collecbags = new HashSet<Collecbags>();
        }
    
        public System.DateTime Date { get; set; }
        public string ID { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public Nullable<double> Weight { get; set; }
        public string Site { get; set; }
        public Nullable<double> WeightFenbo { get; set; }
        public Nullable<double> WeightJisancan { get; set; }
        public Nullable<double> WeightYiji { get; set; }
        public Nullable<double> WeightErji { get; set; }
        public Nullable<double> WeightJipao { get; set; }
        public int ProvinceProvinceID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cost> Cost { get; set; }
        public virtual Province Province { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Collecbags> Collecbags { get; set; }
    }
}
